---
- hosts: all
  gather_facts: yes
  tasks:
  - set_fact:
      mode: "{{ 'static' if ip_add is defined else 'dhcp' }}" 
  - include_task: "centos_iface.yml"
    when: ansible_facts['os_family'] == "RedHat"
  - include_task: "ubuntu_iface.yml"
    when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] >= "18"
